// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type UserCartInput struct {
	UserID      string `json:"UserId"`
	Username    string `json:"Username"`
	Password    string `json:"Password"`
	DateOfBirth string `json:"DateOfBirth"`
	Age         int    `json:"Age"`
	Email       string `json:"Email"`
	CartNumber  int    `json:"CartNumber"`
}
