package resolvers

/*
// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"
	"go-server/graph/model"
)

// GetPerson is the resolver for the getPerson field.
func (r *QueryResolver) GetPerson(ctx context.Context) ([]*model.Person, error) {
	panic(fmt.Errorf("not implemented: GetPerson - getPerson"))
}
*/
