package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"go-server/graph/model"
)

// GetpPet is the resolver for the getpPet field.
func (r *QueryResolver) GetpPet(ctx context.Context) ([]*model.Pet, error) {
	value := []*model.Pet{
		{ID: 13432342, Name: "saad"},
	}

	return value, nil
}
