package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"
	"fmt"
	"go-server/graph/model"
)

// GetPerson is the resolver for the getPerson field.
func (r *queryResolver) GetPerson(ctx context.Context) ([]*model.Person, error) {
	panic(fmt.Errorf("not implemented: GetPerson - getPerson"))
}

// GetpPet is the resolver for the getpPet field.
func (r *queryResolver) GetpPet(ctx context.Context) ([]*model.Pet, error) {
	panic(fmt.Errorf("not implemented: GetpPet - getpPet"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *queryResolver) Person(ctx context.Context) ([]*model.Person, error) {
	panic(fmt.Errorf("not implemented: Person - person"))
}
func (r *queryResolver) Pet(ctx context.Context) ([]*model.Pet, error) {
	panic(fmt.Errorf("not implemented: Pet - pet"))
}
